SET(VERSION 4.10)
SET(ARCH sparc)
SET(BSP leon3)

SET(PATTERN "${ARCH}-rtems${VERSION}")
SET(CMAKE_SYSTEM_NAME ${PATTERN})

find_program (CMAKE_C_COMPILER "${ARCH}-rtems${VERSION}-gcc")
find_program (CMAKE_CXX_COMPILER "${ARCH}-rtems${VERSION}-g++")
find_program (CMAKE_AR "${ARCH}-rtems${VERSION}-ar")
find_program (CMAKE_LINKER "${ARCH}-rtems${VERSION}-ld")

get_filename_component(RTEMS_BIN_PATH  ${CMAKE_CXX_COMPILER}  DIRECTORY)
SET(RTEMS_BASE_PATH "${RTEMS_BIN_PATH}/..")
SET(CMAKE_FIND_ROOT_PATH "${RTEMS_BIN_PATH}/..")

# search for programs in the build host directories
#SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM ONLY)

# for libraries and headers in the target directories
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

SET(INCLUDE_PATH "${RTEMS_BASE_PATH}/${PATTERN}/include")
SET(INCLUDE_PATH_2  "${RTEMS_BASE_PATH}/${PATTERN}/${BSP}/lib/include")

message (STATUS "CMAKE_C_COMPILER = ${CMAKE_C_COMPILER}")
message (STATUS "CMAKE_CXX_COMPILER = ${CMAKE_CXX_COMPILER}")
message (STATUS "CMAKE_FIND_ROOT_PATH = ${CMAKE_FIND_ROOT_PATH}")
message (STATUS "INCLUDE_PATH = ${INCLUDE_PATH}")
message (STATUS "INCLUDE_PATH_2 = ${INCLUDE_PATH_2}")

INCLUDE_DIRECTORIES(${INCLUDE_PATH})
INCLUDE_DIRECTORIES(${INCLUDE_PATH_2})


